### PR TITLE
Modify Game Controller, RSpec tests and 

### PR DESCRIPTION
**Pull request by msarit**

### CODE REVIEW

**Comment by msarit** [comment]
- Updated the game_controller with "initiated_games" and "white_player" methods (instead of "games" and "user" methods)

- Updated the game_model to include "required: false" parameter to the "black_player" line - to avoid an RSpec error that said "Black Player must exist"

- Updated the rspec tests and factorybot factories to reflect game and user model changes

**Comment by Linda091** [comment]
Good to go on my end! I'm assuming you checked that the rspec is functioning properly now.

**Comment by msarit** [comment]
:face-palm: I'm still getting the hang of Pull Requests team - sorry if I have made things confusing. I just added another commit to this PR; it concerns the Game.available scope. I added the scope (and also an "available" method - as advised by RubyDocs) to the Game model. Then I updated the Games controller.

**Comment by jsilvajr1** [comment]
Looks good to me! ::thumbs up::

**Comment by bryanjim** [comment]
👍

**Pull request merged**
