### PR TITLE
Add entire app to branch

### PR DESCRIPTION
**Pull request by msarit**

### CODE REVIEW

**Comment by ilyakrasnov** [comment]
@msarit PR looks great! 👍  The commit message could have been be a bit more informative 😄 sth like 'Add game crud for games' or 'Initial game'.. and/or adding the trello link to the commit message.. it'll help us in future..

**Comment by msarit** [comment]
@ilyakrasnov Thanks Ilya! I'll write better commit msgs in the future 😉

**Comment by Linda091** [comment]
Overall looks great, but I have two questions.

- We both installed the devise gem, but my pull request didn’t state there was a merge conflict. @ilyakrasnov is this because Arit's code hasn’t been merged yet?

- @msarit - I noticed you changed the production & development name in the database.yml from checkmates -> agileapp. @ilyakrasnov do I need to change this too?

**Comment by ilyakrasnov** [comment]
@Linda091 there are no merge conflicts because of 2 reasons:

1. Arit's pr is not merged yet (to master) and Linda's pr is compared to current master (so github doesn't know that there are potential changes.
2. Even if it was merged - merge conflict would only appear if you change the same lines and git can't figure out what changes to take... if you added a gem on line 1 and someone else on line 100, git would have no problem with it.. 

So, regarding devise: it would be advisable to wait for @msarit's  pr to be accepted and merged. Then @Linda091 you can run 

`git pull origin master` from your master branch, then
`git checkout YOUR_BRANCH_WITH_THE_PR`, then
`git merge master`

What it will do is try to incorporate the changes from master into your branch.. You may run into some merge conflict which you'll need to sort out locally and once resolved, you push to your branch thus updating the pr.. As you pointed out, you both added devise for example, but once you do this procedure you'll see that since its already in master, there is no need to add it twice..


Regarding `table names`: Good catch! @msarit lets change back to the state it was before - we can live with renaming the db but it could cause you guys some head ache - so better not do it..


Hope it all makes sense: @jsilvajr1 @bryanjim also tagging you guys here - its an important discussion 😄

**Comment by ilyakrasnov** [comment]
Awesome @msarit lets merge PR#1 👍

**Pull request merged**
